use std::env::VarError;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum ApiError {
    #[error("Network or Request error: {0}")]
    RequestError(#[source] reqwest::Error),

    #[error("Failed to parse URL: {0}")]
    ParseUrlError(#[from] url::ParseError),

    #[error("Failed to parse JSON response: {0}")]
    TransformJSONError(#[from] serde_json::Error),

    #[error("GigaChat API error: Status {status}, Body: {body}")]
    ApiStatusError { status: reqwest::StatusCode, body: String },

    #[error("Certificate file error: {0}")]
    CertIoError(#[from] std::io::Error),

    #[error("Certificate parsing error: {0}")]
    CertParseError(#[source] reqwest::Error),

    #[error("Failed to build GigaChatApiClient: {0}")]
    ApiClientBuildError(#[source] reqwest::Error),

    #[error("Failed to decode response body: {0}")]
    DecodeResponseError(#[source] reqwest::Error),

    #[error("No content was generated by the model")]
    NoContent,
}

#[derive(Error, Debug)]
pub enum BotConfigError {
    #[error("Failed to parse LOG_LEVEL: '{0}' is not a valid level")]
    ParseLogLevelError(String),

    #[error("Environment variable 'TELOXIDE_TOKEN' not found")]
    BotTokenNotFound(#[source] VarError),

    #[error("Environment variable 'GIGACHAT_CLIENT_ID' not found")]
    GigaChatClientIDNotFound(#[source] VarError),

    #[error("Environment variable 'GIGACHAT_CLIENT_SECRET' not found")]
    GigaChatClientSecretNotFound(#[source] VarError),

    #[error("Environment variable 'LOG_LEVEL' not found")]
    LogLevelNotFound(#[source] VarError),
}