use crate::common::Model;
use std::env::VarError;
use teloxide::RequestError;
use teloxide::dispatching::dialogue::InMemStorageError;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum ApiError {
    #[error("Network or Request error: {0}")]
    RequestError(#[source] reqwest::Error),

    #[error("Failed to parse proxy URL error: {0}")]
    ProxyURLError(#[source] reqwest::Error),

    #[error("Failed to parse URL: {0}")]
    ParseUrlError(#[from] url::ParseError),

    #[error("Failed to parse JSON response: {0}")]
    TransformJSONError(#[from] serde_json::Error),

    #[error("API error: Model {model} Status {status}, Body: {body}")]
    ApiStatusError {
        model: Model,
        status: reqwest::StatusCode,
        body: String,
    },

    #[error("Certificate file error: {0}")]
    CertIoError(#[from] std::io::Error),

    #[error("Certificate parsing error: {0}")]
    CertParseError(#[source] reqwest::Error),

    #[error("Failed to build GigaChatApiClient: {0}")]
    ApiClientBuildError(#[source] reqwest::Error),

    #[error("Failed to decode response body: {0}")]
    DecodeResponseError(#[source] reqwest::Error),

    #[error("No content was generated by the model")]
    NoContent,

    #[error("No models were provided")]
    NoModels,

    #[error("Failed to generate content with all available models")]
    GenFailed,

    #[error("Repo error {0}")]
    StorageError(#[from] RepoError),

    #[error("Sticker already exists")]
    StickerAlreadyExists,

    #[error("Sticker not found")]
    StickerNotFound,

    #[error("Telegram API error: {0}")]
    TelegramError(#[from] RequestError),

    #[error("Dialogue storage error: {0}")]
    DialogueStorageError(#[from] InMemStorageError),

    #[error("Command conversion error, unknown command: {0}")]
    CommandConversionError(String),
}

#[derive(Error, Debug)]
pub enum RepoError {
    #[error("Failed to open storage file {0}")]
    FailedToOpenFile(#[source] std::io::Error),

    #[error("Failed to read file {0}")]
    FailedToReadFile(#[source] std::io::Error),

    #[error("Failed to write JSON to file {0}")]
    WriteJSONError(#[source] serde_json::Error),

    #[error("Failed to read JSON from file {0}")]
    ReadJSONError(#[source] serde_json::Error),

    #[error("Failed to change file {0}")]
    ChangeFileError(#[source] std::io::Error),
}

#[derive(Error, Debug)]
pub enum BotConfigError {
    #[error("Failed to parse LOG_LEVEL: '{0}' is not a valid level")]
    ParseLogLevelError(String),

    #[error("Environment variable 'TELOXIDE_TOKEN' not found")]
    BotTokenNotFound(#[source] VarError),

    #[error("Environment variable 'GIGACHAT_CLIENT_ID' not found")]
    GigaChatClientIDNotFound(#[source] VarError),

    #[error("Environment variable 'GIGACHAT_CLIENT_SECRET' not found")]
    GigaChatClientSecretNotFound(#[source] VarError),

    #[error("Environment variable 'MISTRAL_TOKEN' not found")]
    MistralTokenNotFound(#[source] VarError),

    #[error("Environment variable 'XAI_API_KEY' not found")]
    XAITokenNotFound(#[source] VarError),

    #[error("Environment variable 'PROXY_URL' not found")]
    ProxyURLNotFound(#[source] VarError),

    #[error("Environment variable 'LOG_LEVEL' not found")]
    LogLevelNotFound(#[source] VarError),
}
